### PR TITLE
fix ConsoleBot handlerDidEnd

### LINKED ISSUE #251: should not print handlerDidEnd in ConsoleBot fallback mode
```
You > ...
Bot > ...
Bot > handlerDidEnd: []
```

### PR DESCRIPTION
**Pull request by tw0517tw**
fix #251

### CODE REVIEW

File: src/context/ConsoleContext.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ export default class ConsoleContext extends Context implements PlatformContext {
             return target[key];
           }
           // should return undefined when check if it is a promise
-          if (key === 'then') return;
+          if (key === 'then' || key === 'handlerDidEnd') return;
```
Comment (chentsulin) [inline src/context/ConsoleContext.js]: We should have a method blacklist.
