### PR TITLE
Fix persona cli error messages

### LINKED ISSUE #352: Correct messenger persona cli error message
should be `list` instead of `create`
https://github.com/Yoctol/bottender/blob/master/src/cli/providers/messenger/persona.js#L125
should be `delete` instead of `create`
https://github.com/Yoctol/bottender/blob/master/src/cli/providers/messenger/persona.js#L209

### PR DESCRIPTION
**Pull request by kidkcl**
fix #352

### CODE REVIEW

File: src/cli/providers/messenger/persona.js [hunk 1]
```diff
@@ -211,7 +211,7 @@ export async function deletePersona(ctx) {
       print(`Cannot get persona of ID ${bold(personaId)}`);
     }
   } catch (err) {
-    error(`Failed to create ${bold('persona')}`);
+    error(`Failed to delete ${bold('persona')} ${bold(personaId)}`);
```
Comment (Calvin-Lin) [inline src/cli/providers/messenger/persona.js]: Here should add `of ID` for consistency

Comment (kidkcl) [reply src/cli/providers/messenger/persona.js]: I changed both of them to `with ID`.

Comment (Calvin-Lin) [reply src/cli/providers/messenger/persona.js]: I think you specify the ID of the persona to delete. So using `of` is still better in my opinion.
